### PR TITLE
upgrade cert-controller and set restartOnSecretRefresh

### LINKED ISSUE #1372: HNC: upgrade cert-controller and set restartOnSecretRefresh
See https://github.com/open-policy-agent/cert-controller/pull/23. The flag is no longer part of our "batteries included" cert-controller so we need to upgrade it ourselves.

/good-first-issue

### PR DESCRIPTION
**Pull request by frbimo**
fixes #1372 

test:
make test

Update:
see https://github.com/kubernetes-sigs/multi-tenancy/pull/1373#issuecomment-774027206

tested: e2e-test
steps:

    make kind-reboot
    make kind-deploy
    (waiting until webhooks are ready)
    HNC_REPAIR=<local_manifest_path > make test-e2e

### CODE REVIEW

**Comment by adrianludwin** [comment]
/ok-to-test

/assign @yiqigao217 

Yiqi, can you PTAL and review this? Also, @frbimo can you please run the e2e tests on this change? See https://github.com/kubernetes-sigs/multi-tenancy/tree/master/incubator/hnc#development-workflow for details and @yiqigao217 can help you out.

**Comment by adrianludwin** [comment]
/approve

@yiqigao217 will lgtm

**Comment by adrianludwin** [comment]
... @frbimo once you've run the e2e tests, can you please amend the commit message saying so? If this feature is broken, the tests that rely on `HNC_REPAIR` will probably break too, so this is a good test to ensure that everything's working.

Also, manually deploying HNC to an fresh cluster (i.e. one without the `hnc-system` namespace) and manually verifying that the  container restarts itself with the expected message from `cert-controller` would give even more confidence that this is working well.

**Review by yiqigao217 — COMMENTED** [review]
Is it that we have already set this flag by default in the hnc manager pod configuration (saw it in config/manager/manager.yaml), and it's only now getting the flag in HNC and passing it to cert-rotator, instead of cert-rotator getting the flag directly?

Overall the code lgtm and I agree that e2e testing is needed. Please let me know if you have any question on how to run e2e test.

**Comment by adrianludwin** [comment]
@yiqigao217 yup that's exactly it. cert-controller no longer parses that
flag itself (you can see the diff that Github hides by default)

**Comment by frbimo** [comment]
> ... @frbimo once you've run the e2e tests, can you please amend the commit message saying so? If this feature is broken, the tests that rely on `HNC_REPAIR` will probably break too, so this is a good test to ensure that everything's working.
> 
> Also, manually deploying HNC to an fresh cluster (i.e. one without the `hnc-system` namespace) and manually verifying that the container restarts itself with the expected message from `cert-controller` would give even more confidence that this is working well.

is it ok to use local cluster e.g kind?

**Comment by adrianludwin** [comment]
Yup Kind is good!

**Comment by frbimo** [comment]
@adrianludwin  it was failed at point:
```
• Failure [110.684 seconds]
Quickstart
/home/bee/Code/go/src/github.com/frbimo/multi-tenancy/incubator/hnc/test/e2e/quickstart_test.go:11
  Should intergrate hierarchical network policy [It]
  /home/bee/Code/go/src/github.com/frbimo/multi-tenancy/incubator/hnc/test/e2e/quickstart_test.go:105

  Timed out after 60.125s.
  Command: [kubectl run client -n service-1 -i --image=alpine --restart=Never --rm -- sh -c "wget -qO- --timeout 2 http://s2.service-2"]
  failed: exit status 1

  /home/bee/Code/go/src/github.com/frbimo/multi-tenancy/incubator/hnc/test/e2e/quickstart_test.go:125
  ```
  
  k8s v1.19.1

**Comment by frbimo** [comment]
after kind-reset, i can't reproduce it.
Now still testing, but not sure if its make any progress. i dont see any log. Still waiting...

**Comment by frbimo** [comment]
ah, it was failing here:
```
error: unable to recognize "/home/bee/Code/go/src/github.com/frbimo/multi-tenancy/incubator/hnc/manifests/kustomization.yaml": no matches for kind "Kustomization" in version "kustomize.config.k8s.io/v1beta1"

-----------------------------WARNING------------------------------
WARNING: COULDN'T REPAIR HNC: Error: exit status 1
Output: Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```


Then i removed `../manifest/kustomization.yaml` and re-run test from fresh-build Kind cluster.
The reason i remove it was because `make manifests` were using `../manifest/kustomization.yaml` to build `../manifest/hnc-manager.yaml`. And also i dont see the [guideline](https://github.com/kubernetes-sigs/multi-tenancy/tree/master/incubator/hnc#development-workflow) has prerequisite to install `kustomize` into the cluster.
@yiqigao217 is this make sense?

**Comment by frbimo** [comment]
Update:

tested: e2e-test
steps:
- make kind-reboot
- make kind-deploy
(waiting until webhooks are ready)
- HNC_REPAIR=<local_manifest_path > make test-e2e

manually verifiying cert-controller is running seconds after controller pod restarted:
```
{"level":"info","ts":1612529256.6006706,"logger":"cert-rotation","msg":"starting cert rotator controller"}
{"level":"info","ts":1612529256.6006455,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
{"level":"info","ts":1612529256.6007586,"logger":"controller-runtime.manager.controller.cert-rotator","msg":"Starting EventSource","source":{}}
{"level":"info","ts":1612529256.701276,"logger":"controller-runtime.manager.controller.cert-rotator","msg":"Starting EventSource","source":{}}
{"level":"info","ts":1612529256.702513,"logger":"cert-rotation","msg":"no cert refresh needed"}
{"level":"info","ts":1612529256.702632,"logger":"cert-rotation","msg":"certs are ready in /tmp/k8s-webhook-server/serving-certs"}

```

**Comment by frbimo** [comment]
commit amended.
ptal @adrianludwin

**Comment by adrianludwin** [comment]
/lgtm
/hold

@yiqigao217 please remove the hold when you're happy.

Thanks for the fix!

**Review by yiqigao217 — COMMENTED** [review]
/hold cancel

**Pull request merged**
