### PR TITLE
Update the generated role.yaml

### PR DESCRIPTION
**Pull request by yiqigao217**
This update is generated from a previous change.

### CODE REVIEW

**Comment by adrianludwin** [comment]
Looks like this was a consequence of #380  - the old object controller (incorrectly) had these permissions, so when it was deleted, they should have been removed from the generated files as well. Not sure why they weren't 🤷‍♂️

**Comment by yiqigao217** [comment]
> Looks like this was a consequence of #380 - the old object controller (incorrectly) had these permissions, so when it was deleted, they should have been removed from the generated files as well. Not sure why they weren't

Ah now it makes sense. The file was generated then in #380 . See history here: https://github.com/kubernetes-sigs/multi-tenancy/pull/380#pullrequestreview-353199173. We thought it was supposed to be generated from even previous changes and thus excluded from #380

**Pull request merged**
