### PR TITLE
[VC] update tenant master component to v1.16.x

### PR DESCRIPTION
**Pull request by zhuangqh**
Signed-off-by: zhuangqh <zhuangqhc@gmail.com>

### CODE REVIEW

**Comment by christopherhein** [comment]
How do the image registries get updated? 

I'm seeing both `registry.cn-hangzhou.aliyuncs.com/virtualcluster/apiserver-v1.16.2` and `virtualcluster/apiserver-v1.15.4`.

**Comment by ShadowJonathan** [comment]
> How do the image registries get updated?
> 
> I'm seeing both `registry.cn-hangzhou.aliyuncs.com/virtualcluster/...` and `virtualcluster/...`.

This, i also cannot access `registry.cn-hangzhou.aliyuncs.com`, it times out for me.

**Comment by christopherhein** [comment]
I wonder if we should have the same registry domain for all images that come from the `virtualcluster` project. I know for myself I usually build all the images and push them to my own registry then have to change all the paths manually, at least until we have #738 when we can use `kustomize set image name=foobar`.

**Comment by Fei-Guo** [comment]
> I wonder if we should have the same registry domain for all images that come from the `virtualcluster` project. I know for myself I usually build all the images and push them to my own registry then have to change all the paths manually, at least until we have #738 when we can use `kustomize set image name=foobar`.

Yes, we should. @zhuangqh, we'd better change images to docker hub ones for loadbalancer type of clusterversion.

**Comment by zhuangqh** [comment]
fixed. good catch @Fei-Guo @christopherhein

**Pull request merged**
