### PR TITLE
Compute NumSourceObjects in HNCConfiguration status

### PR DESCRIPTION
**Pull request by sophieliu15**
Note: This PR is implemented on top of #542, please review that first. I will rebase and remove the hold once #542 is merged. Thank you! 

This PR computes NumSourceObjects as a part of HNCConfiguration status. NumSourceObjects indicates the number of objects of a specific type created by users.

Tested:unit tests, GKE cluster

Issue: #411

### CODE REVIEW

**Comment by sophieliu15** [comment]
/hold

I will cancel hold once #542 is merged.

**Comment by sophieliu15** [comment]
Unfortunately I don't have enough time to resolve conflicts in this file. :( I will resolve the conflicts and clean it up after I come back from vacation.

**Comment by adrianludwin** [comment]
> Unfortunately I don't have enough time to resolve conflicts in this file. :( I will resolve the conflicts and clean it up after I come back from vacation.

np!

**Comment by sophieliu15** [comment]
This PR is replaced by #584 

Close this PR for now.

**Pull request closed without merging**
