### PR TITLE
Migrate to v1 APIs for CRD, VWH, MWH

### PR DESCRIPTION
**Pull request by yiqigao217**
Part of #1371 

Migrate apiextensions from v1beta1 to v1:
1. Upgrade controller-tools to generate kubebuilder markers to use v1
apis;
2. Replace v1beta1 with v1 in yaml files and patches;
3. Fix schema changes from v1beta1 to v1:
 a) `SideEffects` is required for v1 MWH, VWH;
 b) `AdmissionReviewVersions` is mandatory for v1;
 c) `webhookClientConfig` schema change in CRD;
 d) `conversionReviewVersions` in v1 CRD;
 e) add 1 more level of indention in enum singleton patch;
 f) add `spec.scope` and schema in testing CRD (they are required in v1);
 g) add `v1beta1` to CRD `spec.conversion.conversionReviewVersions` and
 VWH `admissionReviewVersions`, since it's required in K8s 1.16 cluster.
4. E2e test in 1.16 and 1.17 K8s cluster and `make test`(got below issue
and fixed);
5. Reinstall latest kubebuilder since controller-runtime envtest uses
etcd and kube-apiserver loaded by default from
/usr/local/kubebuilder/bin. (TODO will document this in the next PR in
 `make test` and HNC developer README).

### CODE REVIEW

**Review by adrianludwin — COMMENTED** [review]
/lgtm
/approve
/hold
/assign @rjbez17 

Looks great but I wouldn't mind another set of eyes on this

**Comment by yiqigao217** [comment]
/hold

Seems `v1beta1` is required in the CRD `spec.conversion.conversionReviewVersions` and VWH `admissionReviewVersions` in K8s 1.16 cluster. Testing now.

**Comment by yiqigao217** [comment]
> Seems `v1beta1` is required in the CRD `spec.conversion.conversionReviewVersions` and VWH `admissionReviewVersions` in K8s 1.16 cluster. Testing now.

Tested on 1.16 cluster after adding `v1beta1` to the list and it worked. Also retested it in 1.17 cluster and it worked. Updated the PR message to reflect it.

**Comment by rjbez17** [comment]
/lgtm

Did you need the hold still for some testing? Sounds like it's all good but I'll leave it just in case.

**Comment by adrianludwin** [comment]
lgtm as well - @yiqigao217 please cancel the hold when you're comfortable.

**Pull request merged**
