### PR TITLE
Passes new kinds to be inherited

### PR DESCRIPTION
**Pull request by entro-pi**
This commit adds five Kinds to be inherited via their GVK
values.

Test: manually via make manifests then make test.

### CODE REVIEW

**Comment by entro-pi** [comment]
addresses #91

**Comment by adrianludwin** [comment]
For a change like this, I'd like to see manual testing that you can actually create all the new types in a parent namespace and see them show up in a child namespace too. Did you do this?

**Comment by entro-pi** [comment]
I have not! This will require multiple clusters, right? If so, I will have
to wait until after Tuesday to test. I can only run one minikube on this
laptop.

**Comment by adrianludwin** [comment]
I'm not sure why it would need multiple clusters - just multiple namespaces
in a cluster. If you can run the demo (referenced here
<https://github.com/kubernetes-sigs/multi-tenancy/tree/master/incubator/hnc#the-hierarchical-namespace-controller-hnc>),
you should be able to create Network Policies, PSPs, etc just like you
would have created secrets.

**Comment by entro-pi** [comment]
Excellent! I'm still new to kubernetes, this is all so fun!

/approve cancel
/w.i.p.

**Comment by adrianludwin** [comment]
You shouldn't have to set these yourself since you don't have permission to
approve or lgtm a change. The "WIP" label is useful just to communicate to
the other reviewers but it's usually not necessary either (you could also
just close the PR and reopen a new one when you're ready, unless there's a
large discussion you'd like to be part of the _same_ PR).

**Comment by entro-pi** [comment]
NIce, thanks!

With this, I'll probably get to running these tests in the next couple of hours. Is that enough time to warrant closing the PR and re-opening it after?

**Comment by adrianludwin** [comment]
Nah, I'd just leave it open.

**Comment by entro-pi** [comment]
/hold cancel
/approve

Testing completed, commit log updated.
All types propagate! Woohoo!

**Comment by adrianludwin** [comment]
lgtm but I'll let @rjbez17 do the honours

**Pull request merged**
