### PR TITLE
HNC produces double colons on error message

### LINKED ISSUE #1218: HNC: metav1.StatusReasonInvalid produce double colons when formatting error message
metav1.StatusReasonInvalid produces `The request is invalid: : ` which has repeated colons

### PR DESCRIPTION
**Pull request by frbimo**
fixes #1218

tests:
make test
make kind-deploy

### CODE REVIEW

**Review by adrianludwin — COMMENTED** [review]
This lgtm but I'd like @yiqigao217 to take a look as well. Thanks for the change!

/assign @yiqigao217 
/approve

**Review by yiqigao217 — COMMENTED** [review]
The func changes lgtm! But it seems you will also need to change the callers who has, e.g. `deny(invalid,msg)` to `denyInvalid()`?

**Comment by adrianludwin** [comment]
Ah, good point!

**Comment by frbimo** [comment]
> The func changes lgtm! But it seems you will also need to change the callers who has, e.g. `deny(invalid,msg)` to `denyInvalid()`?

hi @yiqigao217 , thanks for the review.
I want to say that since `Field` is related to `k8s.io/apimachinery/pkg/util/validation/field`, i thought its better for denyInvalid not to accept string.

I made some changes, ptal.

**Review by yiqigao217 — COMMENTED** [review]
Nice change, thanks!
/lgtm
/hold
for @adrianludwin to have another look.

**Pull request merged**
