### PR TITLE
Update HC finalizer from hasOwnedNamespace to hasSubnamespace

### PR DESCRIPTION
**Pull request by yiqigao217**
Tested by make test and verified the updated finalizer name in GKE
cluster.

Part of #667

### CODE REVIEW

**Comment by yiqigao217** [comment]
/assign @adrianludwin 
/assign @rjbez17 

This is a minor change to the finalizer name not API.

**Comment by yiqigao217** [comment]
> What happens if you upgrade HNC but objects with the old finalizer already exist? Do we need an upgrade path?

No, it updates the old finalizer since the finalizer on HC is reset every time reconciling HC. I tested on an existing "owner" namespace in the existing cluster and after `make deploy`, the finalizer is updated.

**Comment by adrianludwin** [comment]
Oh, cool! Thanks :)

/approve
/lgtm
/hold
/assign @rjbez17

**Pull request merged**
