### PR TITLE
Regenerate CRD yamls

### PR DESCRIPTION
**Pull request by adrianludwin**
Just ran `make manifests` but nothing else.

Tested: installed HNC

### CODE REVIEW

**Comment by adrianludwin** [comment]
/assign @yiqigao217 
/assign @rjbez17 

I think only one person needs to approve.

**Review by yiqigao217 — COMMENTED** [review]
/lgtm
/hold

Just confirming that this is because of the controller-gen upgrade? Please feel free to release the hold.

**Comment by adrianludwin** [comment]
No, this isn't related to controller-gen. I'm honestly not sure why I'm
getting different results from what's checked in.

**Comment by yiqigao217** [comment]
Discussed offline: it should be from #1093 (upgrade controller-tools), and there's no API conversions PRs merged after that so we didn't run `make manifests`.

/hold cancel

**Pull request merged**
