### PR TITLE
Spelling corrections

### PR DESCRIPTION
**Pull request by wavell**
Spelling corrections

### CODE REVIEW

**Comment by rjbez17** [comment]
Hi @wavell, can you sign the Linux Foundatino CLA? Details here: https://identity.linuxfoundation.org/projects/cncf

/assign @JimBugwadia

**Comment by JimBugwadia** [comment]
Hi @wavell, thanks for the PR! 

It is approved and pending your signature of the Linux Foundatino CLA (see: https://identity.linuxfoundation.org/projects/cncf).

**Comment by rjbez17** [comment]
@JimBugwadia  I think we can just decline this? Seems the author isn't going to sign the CLA?

**Comment by JimBugwadia** [comment]
@rjbez17 - I duplicated @wavell's contributions to https://github.com/kubernetes-sigs/multi-tenancy/pull/800. Please review. Will close this PR.

**Pull request closed without merging**
