### PR TITLE
Closes #275: fix certmanager version

### LINKED ISSUE #275: HNC: Setup dev env | Cert Manager release 0.8.1 yaml file uses apps/v1beta1 Deployment
By following the guides to setup development environment. Running make `kind-reset` to stop any existing KIND cluster and setup a new one, including the cert manager required to run the webhooks fails using kind image `kindest/node:v1.16.3`.

* Command to run:

```bash
make kind-reset
```

* Error:

```bash
unable to recognize "https://github.com/jetstack/cert-manager/releases/download/v0.8.1/cert-manager.yaml": no matches for kind "Deployment" in version "apps/v1beta1"
unable to recognize "https://github.com/jetstack/cert-manager/releases/download/v0.8.1/cert-manager.yaml": no matches for kind "Deployment" in version "apps/v1beta1"
unable to recognize "https://github.com/jetstack/cert-manager/releases/download/v0.8.1/cert-manager.yaml": no matches for kind "Deployment" in version "apps/v1beta1"
make: *** [deploy-prereq] Error 1
```

### PR DESCRIPTION
**Pull request by smileisak**
* This PR closes #275 

* Update certmanager version to `v0.12.0-beta.1`

[UPDATE]
* Update certmanager version to `v0.11.0`

### CODE REVIEW

**Comment by adrianludwin** [comment]
Does the previous stable release (I'm guessing 0.11.0) work too? I'd vaguely prefer to depend on a stable release, not a beta.

**Comment by adrianludwin** [comment]
Thanks for this fix btw! I think this shows I need to update my version of Kind :)

**Comment by rjbez17** [comment]
Yeah it does seem that `v0.11.0` does use `apps/v1`, I'd prefer to use that instead of a pre-release version.

**Comment by smileisak** [comment]
I've updated the version of `cert-manager` to `0.11.0` as a stable version. 
@rjbez17 @srampal  could you please review this PR ? ☺️ 🙏

**Comment by adrianludwin** [comment]
This is great, thanks! Can you please just do one more thing - can you please squash your three commits together into one and force-push it onto the same branch? It'll keep the history much more clear. Thanks.

/ok-to-test

**Comment by smileisak** [comment]
@adrianludwin done ! :)

**Comment by adrianludwin** [comment]
/lgtm
/approved
/hold

Thanks for this change! Let's submit after we get one more reviewer.

For future reference, in the future consider using terms like "_Upgrade_ cert manager version" in the commit message than "_Fix_" since "fix" implies there was a mistake, which (in this case) there wasn't. But it's not worth holding this up for that.

**Comment by adrianludwin** [comment]
Whoops:

/approve

**Pull request merged**
