### PR TITLE
Remove object modified annotation and fix flaky tests

### PR DESCRIPTION
**Pull request by yiqigao217**
a part of #76 and as the next step in 0.1 after this [discussion](https://github.com/kubernetes-sigs/multi-tenancy/pull/183#issuecomment-546472222)

### CODE REVIEW

**Comment by adrianludwin** [comment]
Approving myself since this is a simple removal of functionality.

/approve
/lgtm

**Comment by rjbez17** [comment]
Retroactive

/lgtm
/approve

**Comment by adrianludwin** [comment]
Thanks Ryan, just didn't want to wait. We'll have another go at redesigning
this feature in v0.2.

**Comment by rjbez17** [comment]
No worries! Flaky tests are the bane of my existence.

**Pull request merged**
