### PR TITLE
Add KUBERNETES_SERVICE_HOST env variable to synced pods

### PR DESCRIPTION
**Pull request by salaxander**
Mutates synced pods with:

```
KUBERNETES_SERVICE_HOST=kubernetes
```

### CODE REVIEW

**Comment by Fei-Guo** [comment]
I suggest you change here 
https://github.com/kubernetes-sigs/multi-tenancy/blob/23e6e2489656e0888094810314ae382c5fe0dfcd/incubator/virtualcluster/pkg/syncer/conversion/mutate.go#L275 , which may lead to the least code change. 

Also please add a comment to explain why this special conversion is needed in the code.

**Comment by salaxander** [comment]
> I suggest you change here
> 
> https://github.com/kubernetes-sigs/multi-tenancy/blob/23e6e2489656e0888094810314ae382c5fe0dfcd/incubator/virtualcluster/pkg/syncer/conversion/mutate.go#L275
> 
> , which may lead to the least code change.
> Also please add a comment to explain why this special conversion is needed in the code.
> Btw, please change the copyright year if you touch any old files.

Is this loop just targeting pods that are exposed via services? I think we would want this change to apply to containers that are also not exposed. I'll add a comment as well :)

**Comment by Fei-Guo** [comment]
> > I suggest you change here
> > https://github.com/kubernetes-sigs/multi-tenancy/blob/23e6e2489656e0888094810314ae382c5fe0dfcd/incubator/virtualcluster/pkg/syncer/conversion/mutate.go#L275
> > 
> > , which may lead to the least code change.
> > Also please add a comment to explain why this special conversion is needed in the code.
> > Btw, please change the copyright year if you touch any old files.
> 
> Is this loop just targeting pods that are exposed via services? I think we would want this change to apply to containers that are also not exposed. I'll add a comment as well :)

I believe it targets all Pods since every Pod needs to have Kubernetes service. Correct me if I am wrong.

**Comment by Fei-Guo** [comment]
> @Fei-Guo pushed an update based on your comment :) Tests are still passing

Excellent, a comment would be preferred for the change.

**Comment by salaxander** [comment]
@Fei-Guo added comment, tests still ok

**Pull request merged**
