### PR TITLE
Remove the deprecated `parent` label

### PR DESCRIPTION
**Pull request by adrianludwin**
We've decided to go with the per-namespace singleton for the reasons
described in [1]. As a result, I've removing all references to the
parent label.

Tested: rewrote the HNC demo [2] to use the singleton method and ran
everything. Plus integ tests, etc.

[1] http://bit.ly/k8s-hnc-design#heading=h.yrpwn4o160j7
[2]
https://docs.google.com/document/d/1TUrRBKqjVW-oI0Mj2XZPLct0bnKnjb7Mhj0FIbJRnUc

### CODE REVIEW

**Comment by rjbez17** [comment]
/hold
/lgtm
/approve

@Fei-Guo  feel free to remove hold after your review

**Comment by adrianludwin** [comment]
@Fei-Guo , the `do-not-merge/hold` label is still on this PR, do you know why?

**Comment by adrianludwin** [comment]
Looks like the correct command is `/hold cancel`?

**Comment by Fei-Guo** [comment]
> Looks like the correct command is `/hold cancel`?

Yes. I realized that and edited my comment. I seems that I need to write a new one.

**Pull request merged**
