### PR TITLE
[VC] Add document for tenant dns support

### PR DESCRIPTION
**Pull request by Fei-Guo**
This change adds document to explain how to customize coredns to provide super master cluster IP translation for tenant service domain name.

### CODE REVIEW

**Comment by ShadowJonathan** [comment]
Would it be possible for coreDNS to eventually automatically detect if it should operate in a "virtualized" fashion, or a "normal" fashion?

I'm just musing, as this means that tooling could detect something "wrong" with the coredns deployment and alter it so it has the "latest" image, and thereby breaking the dns resolver in a tenant namespace. If the dns image could be one and the same for normal k8s, this could be avoided.

(I know this is an unlikely hypothetical, i'm just asking if its possible for this functionality to be implemented transparently in the normal dns image, and switch on detection)

**Comment by Fei-Guo** [comment]
> (I know this is an unlikely hypothetical, i'm just asking if its possible for this functionality to be implemented transparently in the normal dns image, and switch on detection)

Good suggestion! I have pushed a new change for this. Please review.
The virtualcluster/coredns:v1.6.8 image is also updated.

**Comment by ShadowJonathan** [comment]
This looks good, but my suggestion was more one to actually consider PRing this into mainstream coreDNS to allow for that image to transparently work in both scenarios. 

To make a PR into mainstream coreDNS when virtualcluster has had it's first release.

**Comment by Fei-Guo** [comment]
> This looks good, but my suggestion was more one to actually consider PRing this into mainstream coreDNS to allow for that image to transparently work in both scenarios.
> 
> To make a PR into mainstream coreDNS when virtualcluster has had it's first release.

This one is a hacky workaround. But I agree in general, we should think about how to make coredns tenant-aware. In my opinion, all tenants should be able to share a dns server if it has isolation mechanisms.

**Pull request merged**
