### PR TITLE
Add an FAQ with requirements and scaling info

### LINKED ISSUE #973: HNC: Question about some limitations of HNC
Currently, I'm working on the system which is based on the HNC. While working on it, I started to wonder about the limitation of HNC. I went through the guide and design doc but I could not find them. The followings are what I want to confirm:

- How many levels can we nest the namespaces?
- How many child namespaces one parent can hold?

If I miss the doc, please redirect me! Thanks.

### LINKED ISSUE #1006: HNC: document HNC's requirements (e.g. version, permissions)
HNC only works for K8s 1.15 and higher; we should make that explicit somewhere. We should also state that it requires very high privileges - this is alluded to in a bunch of places but not actually specified anywhere.

Thanks @rjbez17 for the suggestion.

### PR DESCRIPTION
**Pull request by adrianludwin**
These didn't seem to fit well in "concepts," "how-to" or "best
practices" so I put them into a catch-all topic.

Testing: staged at
https://github.com/adrianludwin/multi-tenancy/tree/docs/incubator/hnc/docs/user-guide

Fixes #973, fixes #1006

### CODE REVIEW

**Comment by adrianludwin** [comment]
Do not submit until #1228 is in
/hold
/assign @GinnyJI 
/assign @yiqigao217 
/assign @rjbez17

**Review by yiqigao217 — COMMENTED** [review]
/lgtm

**Pull request merged**
