### PR TITLE
Corrects path of config.yaml

### LINKED ISSUE #543: [MTB] Error: stat ./config.yaml: no such file or directory
The path of the config file is wrong and it is causing all the tests to fail. The breaking changes were introduced by #499

### PR DESCRIPTION
**Pull request by SomtochiAma**
This pull request fixes #543

### CODE REVIEW

**Comment by phoenixking25** [comment]
@SomtochiAma this fix has already  merged.

**Comment by SomtochiAma** [comment]
@Fei-Guo @JimBugwadia, Following the [readme](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/benchmarks/documentation/run.md) for running the benchmark test.
The two commands for running the test requires different config path
Running locally
`go test ./e2e/tests`
uses this path -> `../../config.yaml`

while this command
`go test -c ./e2e/tests && ./tests.test`
uses this path -> `./config.yaml`

We might need to restructure the code so the user can pass in the path for the config or in such a  way that both commands use the same config path

I am ready to work on either solution. I would like to  hear your thoughts. Thank you!

**Comment by rjbez17** [comment]
@JimBugwadia  can you comment on @SomtochiAma question above?

**Comment by JimBugwadia** [comment]
While we are in heavy development, seems to me that the local test option i.e. `go test ./e2e/tests` is simpler and easier to manage. Lets remove the second option, if you agree.

Longer term, we can consider the best packaging and distribution of the tests for flexibility.

**Pull request merged**
