### PR TITLE
Clean up CritAncestor tests with hasCondition()

### PR DESCRIPTION
**Pull request by yiqigao217**
This commit cleans up CritAncestor tests with the factored out hasCondition() func.

### CODE REVIEW

**Comment by adrianludwin** [comment]
\lgtm
\approved

Simple PR so I'll just approve it

**Comment by yiqigao217** [comment]
Could anyone help with approving the PR? It's still pending. Thanks!

**Comment by adrianludwin** [comment]
\approve

**Comment by adrianludwin** [comment]
Whoops got my slashes mixed up

**Pull request merged**
