### PR TITLE
[WIP]Migrate tenant controller to kubebuilder v2

### PR DESCRIPTION
**Pull request by MartinForReal**
Signed-off-by: Fan Shang Xiang <fanshangxiang@gmail.com>

### CODE REVIEW

**Comment by Fei-Guo** [comment]
@MartinForReal Thanks for working on this! Since this change completely restructure the entire tenant repo, you'd better add a reasonable change description to explain what you have done. Also please edit the README.md to list the proper steps to install/uninstall the tenant crd/controllers with kubebuilder 2.0 architecture. Please also add your testing results in your change description (can be manual tests for webhooks) to verify the existing webhook functionalities are not broken. 

Again, thanks for your great effort of doing this. Let us just follow some great K8s coding conventions to make a change as clearly as possible.

**Comment by MartinForReal** [comment]
Sure, I will work on this. Thanks for the instructions.
/unassign @Fei-Guo
/assign

**Comment by adrianludwin** [comment]
Can we close this?

**Comment by Fei-Guo** [comment]
/close 

We probably will revisit this later.

**Pull request closed without merging**
