### PR TITLE
fix some typo

### PR DESCRIPTION
**Pull request by jjmengze**
Some typos  confuse the readability of the source code, so I fixed them.

### CODE REVIEW

**Comment by adrianludwin** [comment]
Thanks! Can you please break this up into two PRs though? One for incubator/hnc/..., the other for tenancy/...? They're in the same repo but we're trying to keep their history more-or-less separate for now. Thanks!

**Comment by jjmengze** [comment]
awesome, let's me do it .thanks for your review!

**Comment by jjmengze** [comment]
@adrianludwin could you please review this PR again , thanks a lot!!

**Comment by adrianludwin** [comment]
/ok-to-test

@jjmengze, can you please squash your three commits into one and then force-push it to the branch so that there's only one commit in this PR? Once that's done I'll approve. Thanks for making this change!

**Comment by adrianludwin** [comment]
@jjmengze if you click the "details" link and check out the end of the build log, you'll see that there's a legit compilation error. Did you run `make` before submitting?

```
# github.com/kubernetes-sigs/multi-tenancy/incubator/hnc/pkg/validators
pkg/validators/hierarchy.go:274:13: ns.AncestoryNames undefined (type *forest.Namespace has no field or method AncestoryNames)
# github.com/kubernetes-sigs/multi-tenancy/incubator/hnc/pkg/controllers
pkg/controllers/hierarchy_controller.go:279:17: ns.AncestoryNames undefined (type *forest.Namespace has no field or method AncestoryNames)
# github.com/kubernetes-sigs/multi-tenancy/incubator/hnc/pkg/forest
vet: pkg/forest/forest_test.go:66:40: child.AncestoryNames undefined (type *Namespace has no field or method AncestoryNames)
# github.com/kubernetes-sigs/multi-tenancy/incubator/hnc/pkg/validators
vet: pkg/validators/hierarchy.go:274:14: ns.AncestoryNames undefined (type *forest.Namespace has no field or method AncestoryNames)
```

**Comment by jjmengze** [comment]
I am very sorry, I did not notice that other errors have occurred.
I fixed some of the dependency errors but there are other errors in the make process.
Can you please provide me with some comments so that I can continue to fix it thanks!

```
go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.1
go: finding sigs.k8s.io v0.2.1
go: finding sigs.k8s.io/controller-tools/cmd/controller-gen v0.2.1
go: finding sigs.k8s.io/controller-tools/cmd v0.2.1
go: downloading golang.org/x/sys v0.0.0-20190922100055-0a153f010e69
go: extracting golang.org/x/sys v0.0.0-20190922100055-0a153f010e69
# sigs.k8s.io/controller-tools/pkg/webhook
../../../../pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/webhook/parser.go:98:29: undefined: v1beta1.Webhook
../../../../pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/webhook/parser.go:129:9: undefined: v1beta1.Webhook
../../../../pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/webhook/parser.go:161:21: undefined: v1beta1.Webhook
../../../../pkg/mod/sigs.k8s.io/controller-tools@v0.2.1/pkg/webhook/parser.go:162:23: undefined: v1beta1.Webhook
make: *** [controller-gen] Error 2
```

**Comment by rjbez17** [comment]
/assign @adrianludwin 
/assign @rjbez17 

(me as backup).

**Comment by adrianludwin** [comment]
/lgtm
/approve

Thanks for this fix!

**Pull request merged**
