### PR TITLE
Increase memory limits and requests and update docs

### PR DESCRIPTION
**Pull request by yiqigao217**
Increase memory limits to 300M and requests to 150M since we store more
info, e.g. source objects, in the forest now. About 700 namespaces with
10 propagatable objects in each namespace would use about 200M memory
from performance tests.

Add memory usage in user-guide faq docs.

### CODE REVIEW

**Comment by rjbez17** [comment]
Do we have any docs anywhere describing how an end user would determine the recommended limit/request sizes?

**Comment by rjbez17** [comment]
This lgtm other than the one question about docs.

**Comment by adrianludwin** [comment]
Discussed with @yiqigao217 - she's going to add our performance and memory testing results to the FAQ, and also increase the limits slightly as these limits are pretty tight for at least one known real usecase. We're going to go with 150MB request and 300MB limit.

**Pull request merged**
